# Generated by Django 2.2.15 on 2021-11-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=150, verbose_name='Nom du fichier')),
                ('file', models.FileField(max_length=200, null=True, upload_to='files/')),
            ],
        ),
    ]
